My work except Platform generation
Project250-SkyForm/Fly-Chicken-Fly pull request #21
Opened 2024-02-08 09:47 UTC by SaveQaQ

- Delete some absorbed scripts and game objects
- UI, we have a play button, tutorial button, death mode button, and endless mode button
- random obstacles implementation is done
- able to see the lumps change

2024-02-09 05:31 UTC, fardeenfs commented
In the future, please split these issues and open PR for these issues separately.

For now, is this complete and ready to be merged?

2024-02-09 06:35 UTC, SaveQaQ commented
> In the future, please split these issues and open PR for these issues separately.
> 
> For now, is this complete and ready to be merged?

2024-02-09 06:36 UTC, SaveQaQ commented
> > In the future, please split these issues and open PR for these issues separately.
> > For now, is this complete and ready to be merged?

Yes, it should be completed and ready to be merged.

2024-02-09 07:29 UTC, fardeenfs requested changes

2024-02-09 07:29 UTC, fardeenfs commented on Assets/Scripts/PlatformMovement.cs
Potential Merge Conflict with #22

2024-02-10 06:32 UTC, fardeenfs approved these changes

2024-02-10 06:32 UTC, merged